import type { Metadata } from "next";
import { PT_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import { HeaderLink } from "@/components/HeaderLink";
import { Auth0Provider } from "@auth0/nextjs-auth0/client";


const links = [
  { name: "Home", href: "/" },
  { name: "Support", href: "/support" },
  { name: "Shop", href: "/shop" },
]
const ptMono = PT_Mono({
  weight: "400",
  variable: "--font-pt-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable} ${ptMono.variable}  h-full antialiased`}
    >
      <body className="min-h-full flex w-full flex-col justify-center">
        <div className="flex flex-col justify-center items-center">
          <header className="flex w-full h-full z-100 px-8 py-5 flex-row justify-center items-center gap-x-10">
            {links.map((link) => (
            <HeaderLink key={link.name} href={link.href}>
              {link.name}
            </HeaderLink>
          ))}
          </header>
        </div>
        <div className="flex-1 min-h-full flex w-full flex-col justify-center">
          {/* Uncomment below if using auth0 */}
          {/*<Auth0Provider> */}
            {children}
          {/*</Auth0Provider>*/}
        </div>
      </body>
    </html>
  );
}
